### Develop LSTM Models For Univariate Time Series Forecasting

In [74]:

# univariate lstm example
import numpy as np
from numpy import array as array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten


In [75]:
# preparing independent and dependent features
def prepare_data(timeseries_data, n_features):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_features
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [76]:
# define input sequence
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [77]:
print(X),print(y)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [78]:
X.shape

(6, 3)

In [79]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

### Building LSTM Model

In [80]:

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
#model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=300, verbose=1)


Epoch 1/300
6/6 [==============================] - 3s 533ms/step - loss: 32226.0469
Epoch 2/300
6/6 [==============================] - 0s 4ms/step - loss: 32217.4824
Epoch 3/300
6/6 [==============================] - 0s 2ms/step - loss: 32204.0000
Epoch 4/300
6/6 [==============================] - 0s 3ms/step - loss: 32185.2285
Epoch 5/300
6/6 [==============================] - 0s 2ms/step - loss: 32158.7012
Epoch 6/300
6/6 [==============================] - 0s 2ms/step - loss: 32126.7793
Epoch 7/300
6/6 [==============================] - 0s 2ms/step - loss: 32086.7812
Epoch 8/300
6/6 [==============================] - 0s 2ms/step - loss: 32035.6582
Epoch 9/300
6/6 [==============================] - 0s 3ms/step - loss: 31971.8262
Epoch 10/300
6/6 [==============================] - 0s 3ms/step - loss: 31893.9375
Epoch 11/300
6/6 [==============================] - 0s 3ms/step - loss: 31801.6250
Epoch 12/300
6/6 [==============================] - 0s 3ms/step - loss: 31692.8574
Epoch 13/30

6/6 [==============================] - 0s 2ms/step - loss: 51.4483
Epoch 102/300
6/6 [==============================] - 0s 2ms/step - loss: 42.5196
Epoch 103/300
6/6 [==============================] - 0s 2ms/step - loss: 34.3502
Epoch 104/300
6/6 [==============================] - 0s 2ms/step - loss: 27.2997
Epoch 105/300
6/6 [==============================] - 0s 2ms/step - loss: 21.6162
Epoch 106/300
6/6 [==============================] - 0s 3ms/step - loss: 17.4121
Epoch 107/300
6/6 [==============================] - 0s 2ms/step - loss: 14.6731
Epoch 108/300
6/6 [==============================] - 0s 3ms/step - loss: 13.2770
Epoch 109/300
6/6 [==============================] - 0s 2ms/step - loss: 13.0171
Epoch 110/300
6/6 [==============================] - 0s 2ms/step - loss: 13.6311
Epoch 111/300
6/6 [==============================] - 0s 2ms/step - loss: 14.8180
Epoch 112/300
6/6 [==============================] - 0s 4ms/step - loss: 16.3054
Epoch 113/300
6/6 [=======================

Epoch 203/300
6/6 [==============================] - 0s 2ms/step - loss: 12.1387
Epoch 204/300
6/6 [==============================] - 0s 2ms/step - loss: 12.1303
Epoch 205/300
6/6 [==============================] - 0s 2ms/step - loss: 12.1218
Epoch 206/300
6/6 [==============================] - 0s 2ms/step - loss: 12.1130
Epoch 207/300
6/6 [==============================] - 0s 2ms/step - loss: 12.1041
Epoch 208/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0949
Epoch 209/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0856
Epoch 210/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0761
Epoch 211/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0674
Epoch 212/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0591
Epoch 213/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0505
Epoch 214/300
6/6 [==============================] - 0s 2ms/step - loss: 12.0416
Epoch 215/300
6/6 [=========

### Predicting For the next 10 data

In [89]:
# demonstrate prediction for next 10 days
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

[230.26244]
1 day input [196.         210.         230.26243591]
1 day output [[243.8348]]
yhat1 :[243.8348]
yhat2 :243.8348
[187, 196, 210, 230.26244, 243.8348]
2 day input [210.         230.26243591 243.83479309]
2 day output [[262.21713]]
yhat1 :[262.21713]
yhat2 :262.21713
[196, 210, 230.26244, 243.8348, 262.21713]
3 day input [230.26244 243.8348  262.21713]
3 day output [[283.663]]
yhat1 :[283.663]
yhat2 :283.663
[210, 230.26244, 243.8348, 262.21713, 283.663]
4 day input [243.8348  262.21713 283.663  ]
4 day output [[302.2666]]
yhat1 :[302.2666]
yhat2 :302.2666
[230.26244, 243.8348, 262.21713, 283.663, 302.2666]
5 day input [262.21713 283.663   302.2666 ]
5 day output [[324.91632]]
yhat1 :[324.91632]
yhat2 :324.91632
[243.8348, 262.21713, 283.663, 302.2666, 324.91632]
6 day input [283.663   302.2666  324.91632]
6 day output [[349.3842]]
yhat1 :[349.3842]
yhat2 :349.3842
[262.21713, 283.663, 302.2666, 324.91632, 349.3842]
7 day input [302.2666  324.91632 349.3842 ]
7 day output [[3

In [ ]:
timeseries_data

In [ ]:
len(timeseries_data)

In [ ]:
lst_output

In [ ]:
lst

### Visualizaing The Output

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
day_new=np.arange(1,10)
day_pred=np.arange(10,20)

In [ ]:
plt.plot(day_new,timeseries_data)
plt.plot(day_pred,lst_output)
